"""Run backend.services.research_agent.research_club against a diverse set of
real club websites and write a markdown report for manual review.

Not part of the app itself — a one-off QA tool for eyeballing extraction
quality against real, messy websites (per BUILD_PROMPTS.md Step 4: "write a
test ... and print what got extracted ... so we can see how well it's
working on real messy websites"). Picks span business/finance, tech,
pre-professional, arts, and outdoors clubs, and mix independently-hosted
sites with quirky real-world URLs (tracking params, GitHub Pages, blogs) on
purpose.

Usage:
    python -m qa.research_agent_review
"""

from __future__ import annotations

import json
from pathlib import Path

from backend.services.research_agent import research_club

# (club name, website_url) — picked from data/clubs.json for category/site
# diversity. See CLAUDE.md Step 4 status notes for how these were chosen.
# The last 10 lean toward clubs with formal, competitive application cycles
# (consulting/finance/quant/tech) since those are the club types most likely
# to actually post a deadline or info session, per the first round's one hit
# (Cornell Business Analytics Club) also being that type.
TEST_CLUBS = [
    ("Johnson Consulting Club", "https://www.johnsonconsultingclub.com/"),
    ("Cornell Business Analytics Club", "https://www.cornellbusinessanalytics.org/"),
    ("Alpha Kappa Psi", "https://www.akpsicornell.com/"),
    ("Cornell Real Estate Club", "https://www.cornellrealestateclub.com/"),
    ("Absolute A Cappella", "https://cornellabsolute.com/?fbclid=PAZXh0bgNhZW0CMTEAAadC004MnMkezA7-c31U51mO7VLZebD29CsL7klk20r0IDTGYW7VEZwsn-vbgA_aem_RgQCTtijnKH-63yEcIoO6w"),
    ("Black Ivy Pre-Law Society", "https://blackivyprelawsociety.org/"),
    ("Cornell Alpha Fund Club", "https://www.cornellalphafund.org/"),
    ("Cornell XR", "https://cuxr.github.io/"),
    ("Outing Club at Cornell", "https://cornelloutingclub.org/"),
    ("Cornell Advancing Science and Policy Club", "https://blogs.cornell.edu/asap/"),
    ("Cornell Consulting Club", "https://www.cornellconsultingclub.org/"),
    ("180 Degrees Consulting at Cornell University", "https://www.cornell180dc.org"),
    ("Cornell Data Strategy Club", "https://cornelldatastrategy.com/"),
    ("Cornell FinTech Club", "https://www.cornellfintechclub.com/"),
    ("AppDev at Cornell", "https://www.cornellappdev.com/"),
    ("Blockchain at Cornell", "https://www.cornellblockchain.org/"),
    ("Cornell Wall Street Club", "https://www.cornell-wsc.com"),
    ("Investment Banking Club", "https://www.cornell-ib.com/"),
    ("Cornell Algo Trading Club", "https://www.cornellalgo.com/"),
    ("Quant Fund at Cornell", "http://cornellquantfund.org"),
]

OUTPUT_PATH = Path(__file__).resolve().parent / "research_agent_review.md"

FIELD_LABELS = {
    "application_deadline": "Application deadline",
    "next_meeting": "Next meeting",
    "info_session": "Info session",
    "coffee_chat_link": "Coffee chat link",
}


def run() -> None:
    lines = [
        "# research_agent.py manual review",
        "",
        "Generated by `qa/research_agent_review.py`. For each club below: open the "
        "website link yourself, check whether the extracted fields are actually "
        "correct (and that nothing true on the site was missed), and fill in the "
        "**Verified?** row.",
        "",
        "---",
        "",
    ]

    for name, url in TEST_CLUBS:
        print(f"Researching {name}...")
        result = research_club(url)

        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- **Website:** {url}")
        lines.append(f"- **Pages checked:** {', '.join(result.get('pages_checked', [])) or '(fetch failed)'}")
        lines.append(f"- **not_found:** {result['not_found']}")
        if result.get("error"):
            lines.append(f"- **error:** {result['error']}")
        lines.append("")
        lines.append("| Field | Extracted | Verified? (friend fills in) | Notes |")
        lines.append("|---|---|---|---|")
        for field, label in FIELD_LABELS.items():
            value = result.get(field)
            display = value if value else "_null_"
            lines.append(f"| {label} | {display} | ☐ correct ☐ wrong ☐ missed something | |")
        lines.append("")
        lines.append("<details><summary>Raw JSON</summary>\n")
        lines.append("```json")
        lines.append(json.dumps(result, indent=2))
        lines.append("```")
        lines.append("</details>")
        lines.append("")
        lines.append("---")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"\nWrote review file to {OUTPUT_PATH}")


if __name__ == "__main__":
    run()
